# Generated by Django 4.2.2 on 2023-06-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('AUD', 'AUD'), ('AZN', 'AZN'), ('AMD', 'AMD'), ('BYN', 'BYN'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('HUF', 'HUF'), ('KRW', 'KRW'), ('VND', 'VND'), ('HKD', 'HKD'), ('GEL', 'GEL'), ('DKK', 'DKK'), ('AED', 'AED'), ('USD', 'USD'), ('EUR', 'EUR'), ('EGP', 'EGP'), ('INR', 'INR'), ('IDR', 'IDR'), ('KZT', 'KZT'), ('CAD', 'CAD'), ('QAR', 'QAR'), ('KGS', 'KGS'), ('CNY', 'CNY'), ('MDL', 'MDL'), ('NZD', 'NZD'), ('TMT', 'TMT'), ('NOK', 'NOK'), ('PLN', 'PLN'), ('RON', 'RON'), ('XDR', 'XDR'), ('RSD', 'RSD'), ('SGD', 'SGD'), ('TJS', 'TJS'), ('THB', 'THB'), ('TRY', 'TRY'), ('UZS', 'UZS'), ('UAH', 'UAH'), ('GBP', 'GBP'), ('CZK', 'CZK'), ('SEK', 'SEK'), ('CHF', 'CHF'), ('ZAR', 'ZAR'), ('JPY', 'JPY')], max_length=3)),
                ('rubles', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
